name: Generate Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
       - name: generate contribution graph SVGs
         uses: abozanona/pacman-contribution-graph@main
         with:
          github_user_name: luafxrreira
          games: 'pacman,bomberman'
